# Generated by Django 6.0.6 on 2026-07-06 19:25

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("ACTIVATED", "Activated"),
                            ("DEACTIVATED", "Deactivated"),
                            ("PASSWORD_RESET", "Password reset"),
                            ("ROLE_CHANGED", "Role changed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("department_name", models.CharField(blank=True, max_length=120)),
                ("office_location", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "student_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("UPGRADING", "Upgrading"),
                            ("CREDIT_TRANSFER", "Credit Transfer"),
                            ("CONTINUING", "Continuing"),
                        ],
                        default="REGULAR",
                        max_length=30,
                    ),
                ),
                (
                    "academic_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("GRADUATED", "Graduated"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                (
                    "current_academic_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Year I"),
                            (2, "Year II"),
                            (3, "Year III"),
                            (4, "Year IV"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "admission_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active_student", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["registration_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name", "username"]},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("IT_ADMIN", "IT Administrator"),
                    ("LECTURER", "Lecturer"),
                    ("LAB_COORDINATOR", "Skills Lab Coordinator"),
                    ("ADMINISTRATION", "Administration"),
                    ("STUDENT", "Student"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddField(
            model_name="accountactionlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_actions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountactionlog",
            name="target_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_action_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="accountactionlog",
            index=models.Index(fields=["action"], name="accounts_ac_action_495ecc_idx"),
        ),
        migrations.AddIndex(
            model_name="accountactionlog",
            index=models.Index(
                fields=["created_at"], name="accounts_ac_created_e2b12e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["staff_number"], name="accounts_st_staff_n_4084de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["department_name"], name="accounts_st_departm_8677a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["registration_number"], name="accounts_st_registr_f1a35a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["student_type"], name="accounts_st_student_2c312b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["academic_status"], name="accounts_st_academi_f2d7d2_idx"
            ),
        ),
    ]
