# Generated by Django 6.0.6 on 2026-07-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0002_accountactionlog_staffprofile_studentprofile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="accounts_st_registr_f1a35a_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="accounts_st_student_2c312b_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="accounts_st_academi_f2d7d2_idx",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_profiles",
                to="academics.cohort",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_profiles",
                to="academics.program",
            ),
        ),
    ]
