# Generated by Django 6.0.6 on 2026-07-08 08:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=50)),
                ("intake_year", models.PositiveSmallIntegerField()),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("SUSPENDED", "Suspended"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["-intake_year", "program__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "faculties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="academic_year_end_after_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="unique_current_academic_year",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="academics.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["faculty__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=180)),
                (
                    "year_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Year I"),
                            (2, "Year II"),
                            (3, "Year III"),
                            (4, "Year IV"),
                        ]
                    ),
                ),
                (
                    "semester_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Semester I"),
                            (2, "Semester II"),
                            (3, "Special Semester"),
                        ]
                    ),
                ),
                ("credits", models.PositiveSmallIntegerField(default=0)),
                (
                    "attendance_requirement",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80.00"), max_digits=5
                    ),
                ),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("60.00"), max_digits=5
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unlocks_modules",
                        to="academics.module",
                    ),
                ),
            ],
            options={
                "ordering": ["program__name", "year_level", "semester_number", "code"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_institution", models.CharField(max_length=180)),
                ("previous_module_name", models.CharField(max_length=180)),
                (
                    "previous_mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "supporting_file",
                    models.FileField(
                        blank=True, null=True, upload_to="credit-transfers/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["IT_ADMIN", "ADMINISTRATION"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_credit_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_transfers",
                        to="academics.module",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModuleOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=30,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_offerings",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="module_offerings",
                        to="academics.cohort",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": [
                                "LECTURER",
                                "LAB_COORDINATOR",
                                "ADMINISTRATION",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_module_offerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="academics.module",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-academic_year__start_date",
                    "semester__semester_number",
                    "module__code",
                ],
            },
        ),
        migrations.CreateModel(
            name="ModuleEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("REPEATING", "Repeating"),
                            ("CREDIT_TRANSFER", "Credit Transfer"),
                            ("CONTINUING", "Continuing"),
                        ],
                        default="NORMAL",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Enrolled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                            ("EXEMPTED", "Exempted"),
                        ],
                        default="ENROLLED",
                        max_length=30,
                    ),
                ),
                (
                    "enrolled_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academics.moduleoffering",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "module_offering",
                    "student__first_name",
                    "student__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "minimum_required_practices",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="academics.module",
                    ),
                ),
            ],
            options={
                "ordering": ["module__code", "code", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("required_count", models.PositiveSmallIntegerField(default=1)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_requirements",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offering_requirements",
                        to="academics.procedure",
                    ),
                ),
            ],
            options={
                "ordering": ["module_offering", "procedure__code"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "award_type",
                    models.CharField(
                        choices=[
                            ("CERTIFICATE", "Certificate"),
                            ("DIPLOMA", "Diploma"),
                            ("ADVANCED_DIPLOMA", "Advanced Diploma"),
                            ("BACHELOR", "Bachelor"),
                            ("MASTER", "Master"),
                        ],
                        default="BACHELOR",
                        max_length=40,
                    ),
                ),
                ("duration_years", models.PositiveSmallIntegerField(default=3)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="module",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modules",
                to="academics.program",
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohorts",
                to="academics.program",
            ),
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "semester_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Semester I"),
                            (2, "Semester II"),
                            (3, "Special Semester"),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="semesters",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__start_date", "semester_number"],
            },
        ),
        migrations.AddField(
            model_name="moduleoffering",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_offerings",
                to="academics.semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("faculty", "code"), name="unique_department_code_per_faculty"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("faculty", "name"), name="unique_department_name_per_faculty"
            ),
        ),
        migrations.AddConstraint(
            model_name="credittransfer",
            constraint=models.UniqueConstraint(
                fields=("student", "module"),
                name="unique_credit_transfer_per_student_module",
            ),
        ),
        migrations.AddConstraint(
            model_name="credittransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_mark__isnull", True),
                    models.Q(("previous_mark__gte", 0), ("previous_mark__lte", 100)),
                    _connector="OR",
                ),
                name="credit_transfer_mark_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "module_offering"),
                name="unique_student_module_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedure",
            constraint=models.UniqueConstraint(
                fields=("module", "code"), name="unique_procedure_code_per_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurerequirement",
            constraint=models.UniqueConstraint(
                fields=("module_offering", "procedure"),
                name="unique_procedure_requirement_per_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("department", "name"), name="unique_program_name_per_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("program", "code"), name="unique_module_code_per_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attendance_requirement__gte", 0),
                    ("attendance_requirement__lte", 100),
                ),
                name="module_attendance_requirement_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(("pass_mark__gte", 0), ("pass_mark__lte", 100)),
                name="module_pass_mark_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                fields=("program", "code"), name="unique_cohort_code_per_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="semester_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "semester_number"),
                name="unique_semester_number_per_academic_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("is_current",),
                name="unique_current_semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleoffering",
            constraint=models.UniqueConstraint(
                fields=("module", "cohort", "academic_year", "semester"),
                name="unique_module_offering_per_period",
            ),
        ),
    ]
