# Generated by Django 6.0.6 on 2026-07-15 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("DOWNLOAD", "Download"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("PUBLISH", "Publish"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("MARK_CHANGE", "Mark Change"),
                            ("ATTENDANCE_CHANGE", "Attendance Change"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("app_label", models.CharField(blank=True, max_length=80)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("target_object_id", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("request_method", models.CharField(blank=True, max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="core_auditl_action_d9fb24_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_auditl_created_dc23ea_idx"
                    ),
                    models.Index(
                        fields=["app_label", "model_name"],
                        name="core_auditl_app_lab_2f0dea_idx",
                    ),
                ],
            },
        ),
    ]
