# Generated by Django 6.0.6 on 2026-07-12 20:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OSCERubricItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criterion", models.CharField(max_length=255)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item_order", models.PositiveSmallIntegerField(default=1)),
                ("is_critical", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["station", "item_order"],
            },
        ),
        migrations.CreateModel(
            name="OSCEExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("RESULTS_APPROVED", "Results Approved"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_osce_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_osce_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="osce_exams",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_osce_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-exam_date", "module_offering__module__code"],
            },
        ),
        migrations.CreateModel(
            name="OSCEAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("FIRST_ATTEMPT", "First Attempt"),
                            ("RETAKE", "Retake"),
                        ],
                        default="FIRST_ATTEMPT",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_osce_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="osce_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_osce_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "osce_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.osceexam",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "osce_exam",
                    "student__student_profile__registration_number",
                    "attempt_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="OSCEResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "total_possible_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "final_mark",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("60.00"), max_digits=5
                    ),
                ),
                ("is_passed", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_osce_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="assessments.osceattempt",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "attempt__osce_exam",
                    "attempt__student__student_profile__registration_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="OSCEStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("station_order", models.PositiveSmallIntegerField(default=1)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=10)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=6
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "osce_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="assessments.osceexam",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="osce_stations",
                        to="academics.procedure",
                    ),
                ),
            ],
            options={
                "ordering": ["osce_exam", "station_order"],
            },
        ),
        migrations.CreateModel(
            name="OSCEScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessments.osceattempt",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_osce_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubric_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessments.oscerubricitem",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessments.oscestation",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "attempt",
                    "station__station_order",
                    "rubric_item__item_order",
                ],
            },
        ),
        migrations.AddField(
            model_name="oscerubricitem",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_items",
                to="assessments.oscestation",
            ),
        ),
        migrations.CreateModel(
            name="RetakeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_retake_request",
                        to="assessments.osceattempt",
                    ),
                ),
                (
                    "original_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retake_requests",
                        to="assessments.osceattempt",
                    ),
                ),
                (
                    "osce_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retake_requests",
                        to="assessments.osceexam",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_retake_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retake_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="osceexam",
            index=models.Index(fields=["status"], name="assessments_status_f9119a_idx"),
        ),
        migrations.AddIndex(
            model_name="osceexam",
            index=models.Index(
                fields=["exam_date"], name="assessments_exam_da_37b6e2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="osceexam",
            constraint=models.UniqueConstraint(
                fields=("module_offering", "title", "exam_date"),
                name="unique_osce_exam_per_module_title_date",
            ),
        ),
        migrations.AddIndex(
            model_name="osceattempt",
            index=models.Index(
                fields=["attempt_type"], name="assessments_attempt_fc9040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="osceattempt",
            index=models.Index(fields=["status"], name="assessments_status_1a63e9_idx"),
        ),
        migrations.AddConstraint(
            model_name="osceattempt",
            constraint=models.UniqueConstraint(
                fields=("osce_exam", "student", "attempt_number"),
                name="unique_osce_attempt_number_per_student_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="osceresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("percentage__gte", 0), ("percentage__lte", 100)),
                name="osce_percentage_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="osceresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_mark__gte", 0), ("final_mark__lte", 100)),
                name="osce_final_mark_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="oscestation",
            constraint=models.UniqueConstraint(
                fields=("osce_exam", "station_order"),
                name="unique_station_order_per_osce_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="oscestation",
            constraint=models.UniqueConstraint(
                fields=("osce_exam", "procedure"), name="unique_procedure_per_osce_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="oscestation",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_score__gt", 0)),
                name="osce_station_max_score_greater_than_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="oscescore",
            constraint=models.UniqueConstraint(
                fields=("attempt", "rubric_item"),
                name="unique_score_per_attempt_rubric_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="oscescore",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0)),
                name="osce_score_greater_or_equal_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="oscerubricitem",
            constraint=models.UniqueConstraint(
                fields=("station", "item_order"),
                name="unique_rubric_item_order_per_station",
            ),
        ),
        migrations.AddConstraint(
            model_name="oscerubricitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_score__gt", 0)),
                name="rubric_item_max_score_greater_than_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="retakerequest",
            constraint=models.UniqueConstraint(
                fields=("student", "osce_exam", "original_attempt"),
                name="unique_retake_request_per_failed_attempt",
            ),
        ),
    ]
