# Generated by Django 6.0.6 on 2026-07-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importer_type",
                    models.CharField(
                        choices=[
                            ("STUDENTS", "Students"),
                            ("STAFF", "Staff / Lecturers"),
                            ("MODULES", "Modules"),
                            ("PROCEDURES", "Procedures"),
                            ("LAB_ROOMS", "Lab rooms"),
                        ],
                        max_length=40,
                    ),
                ),
                ("file", models.FileField(upload_to="imports/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATED", "Validated"),
                            ("PARTIALLY_IMPORTED", "Partially imported"),
                            ("IMPORTED", "Imported"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=40,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("IMPORTED", "Imported"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="bulk_imports.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"),
                        name="unique_row_number_per_import_batch",
                    )
                ],
            },
        ),
    ]
