# Generated by Django 6.0.6 on 2026-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulk_imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="importer_type",
            field=models.CharField(
                choices=[
                    ("STUDENTS", "Students"),
                    ("STAFF", "Staff / Lecturers"),
                    ("MODULES", "Modules"),
                    ("PROCEDURES", "Procedures"),
                    ("LAB_ROOMS", "Lab rooms"),
                    ("ATTENDANCE", "Demonstration attendance"),
                ],
                max_length=40,
            ),
        ),
    ]
