# Generated by Django 6.0.6 on 2026-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulk_imports", "0002_alter_importbatch_importer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="importer_type",
            field=models.CharField(
                choices=[
                    ("STUDENTS", "Students"),
                    ("STAFF", "Staff / Lecturers"),
                    ("MODULES", "Modules"),
                    ("PROCEDURES", "Procedures"),
                    ("LAB_ROOMS", "Lab rooms"),
                    ("ATTENDANCE", "Demonstration attendance"),
                    ("INVENTORY_CATEGORIES", "Inventory categories"),
                    ("SUPPLIERS", "Suppliers"),
                    ("STOCK_ITEMS", "Stock items"),
                    ("STOCK_BATCHES", "Stock batches"),
                ],
                max_length=40,
            ),
        ),
    ]
