# Generated by Django 6.0.6 on 2026-07-15 16:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("labs", "0002_selfpracticesession_selfpracticeprocedure_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "inventory categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("contact_person", models.CharField(blank=True, max_length=120)),
                ("phone_number", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_context",
                    models.CharField(
                        choices=[
                            ("DEMONSTRATION", "Demonstration"),
                            ("SELF_PRACTICE", "Self-practice"),
                            ("OSCE", "OSCE"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=40,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_inventory_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demonstration_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_usages",
                        to="labs.demonstrationsession",
                    ),
                ),
                (
                    "osce_exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_usages",
                        to="assessments.osceexam",
                    ),
                ),
                (
                    "self_practice_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_usages",
                        to="labs.selfpracticesession",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_inventory_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=60, unique=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CONSUMABLE", "Consumable"),
                            ("EQUIPMENT", "Equipment"),
                            ("MODEL", "Model / Mannequin"),
                            ("PPE", "PPE"),
                            ("OTHER", "Other"),
                        ],
                        default="CONSUMABLE",
                        max_length=40,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PIECE", "Piece"),
                            ("BOX", "Box"),
                            ("PACK", "Pack"),
                            ("PAIR", "Pair"),
                            ("BOTTLE", "Bottle"),
                            ("LITER", "Liter"),
                            ("MILLILITER", "Milliliter"),
                            ("GRAM", "Gram"),
                            ("KILOGRAM", "Kilogram"),
                            ("SET", "Set"),
                        ],
                        default="PIECE",
                        max_length=40,
                    ),
                ),
                (
                    "minimum_stock_level",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="inventory.inventorycategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_number", models.CharField(max_length=80)),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "received_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("EXHAUSTED", "Exhausted"),
                            ("EXPIRED", "Expired"),
                            ("QUARANTINED", "Quarantined"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_batches",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "received_at", "batch_number"],
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("threshold", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("IGNORED", "Ignored"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_low_stock_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="low_stock_alerts",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryUsageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_approved",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventoryusage",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_items",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["stock_item__name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("ADJUSTMENT_IN", "Adjustment In"),
                            ("ADJUSTMENT_OUT", "Adjustment Out"),
                            ("DAMAGED", "Damaged"),
                            ("EXPIRED", "Expired"),
                            ("RETURNED", "Returned"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField(blank=True)),
                ("reference", models.CharField(blank=True, max_length=120)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockbatch",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryusage",
            index=models.Index(fields=["status"], name="inventory_i_status_d6d8a8_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryusage",
            index=models.Index(
                fields=["usage_context"], name="inventory_i_usage_c_735698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryusage",
            index=models.Index(
                fields=["submitted_at"], name="inventory_i_submitt_767428_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["code"], name="inventory_s_code_73c104_idx"),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(
                fields=["item_type"], name="inventory_s_item_ty_9e06c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(
                fields=["is_active"], name="inventory_s_is_acti_e30616_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock_level__gte", 0)),
                name="stock_item_minimum_level_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("reorder_level__gte", 0)),
                name="stock_item_reorder_level_gte_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(fields=["status"], name="inventory_l_status_63f299_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryusageitem",
            constraint=models.UniqueConstraint(
                fields=("usage", "stock_item"),
                name="unique_stock_item_per_inventory_usage",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryusageitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_requested__gt", 0)),
                name="usage_item_quantity_requested_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryusageitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_approved__gte", 0)),
                name="usage_item_quantity_approved_gte_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_s_movemen_018f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["performed_at"], name="inventory_s_perform_15c0cc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stock_movement_quantity_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.UniqueConstraint(
                fields=("stock_item", "batch_number"),
                name="unique_batch_number_per_stock_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_received__gte", 0)),
                name="stock_batch_quantity_received_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_remaining__gte", 0)),
                name="stock_batch_quantity_remaining_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="stock_batch_unit_cost_gte_zero",
            ),
        ),
    ]
