# Generated by Django 6.0.6 on 2026-07-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemonstrationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demonstration_session",
                        to="bookings.labbooking",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        limit_choices_to={"role": "LECTURER"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demonstration_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demonstration_sessions",
                        to="academics.moduleoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["booking__start_at"],
            },
        ),
        migrations.CreateModel(
            name="LabRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="labs_labroo_code_f3638d_idx"),
                    models.Index(
                        fields=["is_active"], name="labs_labroo_is_acti_12e87d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DemonstrationProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demonstration_sessions",
                        to="academics.procedure",
                    ),
                ),
                (
                    "demonstration_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_procedures",
                        to="labs.demonstrationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["procedure__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("demonstration_session", "procedure"),
                        name="unique_procedure_per_demonstration_session",
                    )
                ],
            },
        ),
    ]
