# Generated by Django 6.0.6 on 2026-07-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("bookings", "0002_initial"),
        ("labs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfPracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectives", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_practice_session",
                        to="bookings.labbooking",
                    ),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="self_practice_sessions",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": [
                                "LECTURER",
                                "LAB_COORDINATOR",
                                "ADMINISTRATION",
                                "IT_ADMIN",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_self_practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["booking__start_at"],
            },
        ),
        migrations.CreateModel(
            name="SelfPracticeProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="self_practice_sessions",
                        to="academics.procedure",
                    ),
                ),
                (
                    "self_practice_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_procedures",
                        to="labs.selfpracticesession",
                    ),
                ),
            ],
            options={
                "ordering": ["procedure__code"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performed_count", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_logs",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_logs",
                        to="academics.procedure",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_procedure_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "self_practice_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_logs",
                        to="labs.selfpracticesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "procedure__code"],
            },
        ),
        migrations.AddIndex(
            model_name="selfpracticesession",
            index=models.Index(fields=["status"], name="labs_selfpr_status_cea417_idx"),
        ),
        migrations.AddConstraint(
            model_name="selfpracticeprocedure",
            constraint=models.UniqueConstraint(
                fields=("self_practice_session", "procedure"),
                name="unique_procedure_per_self_practice_session",
            ),
        ),
        migrations.AddIndex(
            model_name="procedurelog",
            index=models.Index(fields=["status"], name="labs_proced_status_97a271_idx"),
        ),
        migrations.AddIndex(
            model_name="procedurelog",
            index=models.Index(
                fields=["created_at"], name="labs_proced_created_3f0d65_idx"
            ),
        ),
    ]
