# Generated by Django 6.0.6 on 2026-07-11 07:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("labs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNMARKED", "Unmarked"),
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        db_index=True,
                        default="UNMARKED",
                        max_length=30,
                    ),
                ),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demonstration_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="labs.demonstrationsession",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_demonstration_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demonstration_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "demonstration_session__booking__start_at",
                    "student__student_profile__registration_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNMARKED", "Unmarked"),
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("UNMARKED", "Unmarked"),
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_remarks", models.TextField(blank=True)),
                ("new_remarks", models.TextField(blank=True)),
                ("change_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EligibilitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_completed_sessions", models.PositiveIntegerField(default=0)),
                ("attended_sessions", models.PositiveIntegerField(default=0)),
                ("excused_sessions", models.PositiveIntegerField(default=0)),
                ("absent_sessions", models.PositiveIntegerField(default=0)),
                ("unmarked_sessions", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "required_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80.00"), max_digits=5
                    ),
                ),
                ("is_self_practice_eligible", models.BooleanField(default=False)),
                ("is_osce_eligible", models.BooleanField(default=False)),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_snapshots",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "module_offering",
                    "student__student_profile__registration_number",
                ],
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["status"], name="attendance__status_741eb8_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["recorded_at"], name="attendance__recorde_614bf9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                fields=("student", "demonstration_session"),
                name="unique_student_attendance_per_demonstration",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilitysnapshot",
            constraint=models.UniqueConstraint(
                fields=("student", "module_offering"),
                name="unique_eligibility_snapshot_per_student_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilitysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attendance_percentage__gte", 0),
                    ("attendance_percentage__lte", 100),
                ),
                name="eligibility_percentage_between_0_and_100",
            ),
        ),
    ]
