# Generated by Django 6.0.6 on 2026-07-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_selfpracticeattendancerecord"),
        ("labs", "0002_selfpracticesession_selfpracticeprocedure_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="selfpracticeattendancerecord",
            name="self_practice_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_record",
                to="labs.selfpracticesession",
            ),
        ),
        migrations.AddField(
            model_name="selfpracticeattendancerecord",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_practice_attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="selfpracticeattendancerecord",
            index=models.Index(fields=["status"], name="attendance__status_2c279c_idx"),
        ),
        migrations.AddIndex(
            model_name="selfpracticeattendancerecord",
            index=models.Index(
                fields=["recorded_at"], name="attendance__recorde_9cae22_idx"
            ),
        ),
    ]
