# Generated by Django 6.0.6 on 2026-07-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("bookings", "0001_initial"),
        ("labs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labbooking",
            name="lab_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="labs.labroom",
            ),
        ),
        migrations.AddField(
            model_name="labbooking",
            name="module_offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_bookings",
                to="academics.moduleoffering",
            ),
        ),
        migrations.AddField(
            model_name="labbooking",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_lab_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingdecisionlog",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_logs",
                to="bookings.labbooking",
            ),
        ),
        migrations.AddIndex(
            model_name="labbooking",
            index=models.Index(fields=["status"], name="bookings_la_status_7a17f9_idx"),
        ),
        migrations.AddIndex(
            model_name="labbooking",
            index=models.Index(
                fields=["booking_type"], name="bookings_la_booking_cf91cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labbooking",
            index=models.Index(
                fields=["start_at", "end_at"], name="bookings_la_start_a_c26348_idx"
            ),
        ),
    ]
