# Generated by Django 6.0.6 on 2026-07-15 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("facility_name", models.CharField(max_length=180)),
                ("department_or_unit", models.CharField(blank=True, max_length=180)),
                ("clinical_start_date", models.DateField()),
                ("clinical_end_date", models.DateField(blank=True, null=True)),
                ("activities_performed", models.TextField()),
                ("skills_practiced", models.TextField(blank=True)),
                ("reflection", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("supervisor_name", models.CharField(blank=True, max_length=180)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="clinical-reports/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_reports",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_clinical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalTeachingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("facility_name", models.CharField(max_length=180)),
                ("department_or_unit", models.CharField(blank=True, max_length=180)),
                ("teaching_date", models.DateField()),
                ("topic_taught", models.CharField(max_length=180)),
                ("students_supervised_count", models.PositiveIntegerField(default=0)),
                ("objectives", models.TextField(blank=True)),
                ("teaching_activities", models.TextField()),
                ("observations", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="clinical-teaching-reports/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        limit_choices_to={"role": "LECTURER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_teaching_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_teaching_reports",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_clinical_teaching_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-teaching_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Attendance"),
                            ("SELF_PRACTICE", "Self-practice"),
                            ("PROCEDURE_LOG", "Procedure Log"),
                            ("OSCE_RESULT", "OSCE Result"),
                            ("CLINICAL_REPORT", "Clinical Report"),
                            ("CREDIT_TRANSFER", "Credit Transfer"),
                            ("MANUAL_EVIDENCE", "Manual Evidence"),
                            ("OTHER", "Other"),
                        ],
                        default="MANUAL_EVIDENCE",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True, null=True, upload_to="portfolio-evidence/%Y/%m/"
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("is_visible_to_student", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_portfolio_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_items",
                        to="academics.moduleoffering",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "clinical_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reports.clinicalreport",
                    ),
                ),
                (
                    "clinical_teaching_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reports.clinicalteachingreport",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clinicalreport",
            index=models.Index(fields=["status"], name="reports_cli_status_4b7870_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicalreport",
            index=models.Index(
                fields=["clinical_start_date"], name="reports_cli_clinica_450435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalteachingreport",
            index=models.Index(fields=["status"], name="reports_cli_status_c8d100_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicalteachingreport",
            index=models.Index(
                fields=["teaching_date"], name="reports_cli_teachin_bc93ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioitem",
            index=models.Index(
                fields=["item_type"], name="reports_por_item_ty_3614c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioitem",
            index=models.Index(
                fields=["created_at"], name="reports_por_created_3579b5_idx"
            ),
        ),
    ]
